# Generated by Django 5.1.4 on 2026-03-06 13:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7, unique=True)),
                ('total_expected', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=10)),
                ('total_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_complete', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buying_member', models.ForeignKey(blank=True, help_text='Member whose demat account is used this month', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buying_months', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Pool',
                'verbose_name_plural': 'Monthly Pools',
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(help_text='Month in YYYY-MM format (e.g., 2026-03)', max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('partial', 'Partial')], default='unpaid', max_length=10)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contribution',
                'verbose_name_plural': 'Contributions',
                'ordering': ['-month', 'member__name'],
                'unique_together': {('member', 'month')},
            },
        ),
    ]
