# Generated by Django 5.1.4 on 2026-09-10 06:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="base_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1000.00"),
                help_text="Standard monthly share before any buyer top-up.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="contribution",
            name="buyer_topup",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Extra cash this member put in from their own pocket because the month's share purchase cost more than the pool collected. Included in amount, so it does increase ownership %.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="contribution",
            name="carry_forward",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Unspent pool cash this member is still holding from the month they were the buyer. Payable now, but NOT new capital - it was already counted as a contribution in the month it was collected.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="monthlypool",
            name="is_settled",
            field=models.BooleanField(
                default=False,
                help_text="True once the collected-vs-spent difference has been applied.",
            ),
        ),
        migrations.AddField(
            model_name="monthlypool",
            name="total_invested",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Actual cost of shares bought in this month, including brokerage.",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1000.00"),
                help_text="New capital contributed this month. Drives ownership %.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
