# Generated by Django 5.1.4 on 2026-09-10 07:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "contributions",
            "0002_contribution_base_amount_contribution_buyer_topup_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="advance_credit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Reimbursement of an advance this member made in an earlier month. Subtracted from their standard share, so amount = base_amount - this.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="buyer_topup",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Extra cash this member advanced from their own pocket because the month's share purchase cost more than the pool collected. It is reimbursed by reducing their next installment.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
