# Generated by Django 5.1.4 on 2026-09-10 11:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0004_release_pool_cash_from_buyers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="carry_forward",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Extra cash this member owes on top of their share, payable now but NOT new capital. Settlement no longer sets this: unspent pool money stays in the pool for the next purchase instead of being billed to the buyer. Left for an admin to record a one-off amount by hand.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
