# Generated by Django 5.1.4 on 2026-03-06 13:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dividend_per_share', models.DecimalField(decimal_places=2, help_text='Dividend amount per share', max_digits=10)),
                ('total_dividend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Auto-calculated: dividend_per_share × quantity', max_digits=12)),
                ('ex_date', models.DateField(help_text='Ex-dividend date')),
                ('payment_date', models.DateField(blank=True, help_text='Date dividend was paid', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='investments.stock')),
            ],
            options={
                'verbose_name': 'Dividend',
                'verbose_name_plural': 'Dividends',
                'ordering': ['-ex_date'],
            },
        ),
    ]
