--
-- PostgreSQL database dump
--

\restrict 6sMHHmxunKIjLQUeQbXNjyfM1chNIHv55Gy9uUVjEONDbfsVV2RPoElwtsnWwD6

-- Dumped from database version 17.8 (ad62774)
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts_member; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.accounts_member (
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    phone character varying(15) NOT NULL,
    email character varying(254),
    role character varying(10) NOT NULL,
    avatar_color character varying(7) NOT NULL,
    is_active boolean NOT NULL,
    is_staff boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.accounts_member OWNER TO neondb_owner;

--
-- Name: accounts_member_groups; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.accounts_member_groups (
    id bigint NOT NULL,
    member_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.accounts_member_groups OWNER TO neondb_owner;

--
-- Name: accounts_member_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.accounts_member_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_member_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_member_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.accounts_member ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_member_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_member_user_permissions; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.accounts_member_user_permissions (
    id bigint NOT NULL,
    member_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.accounts_member_user_permissions OWNER TO neondb_owner;

--
-- Name: accounts_member_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.accounts_member_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_member_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO neondb_owner;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO neondb_owner;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO neondb_owner;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contributions_contribution; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.contributions_contribution (
    id bigint NOT NULL,
    month character varying(7) NOT NULL,
    amount numeric(10,2) NOT NULL,
    status character varying(10) NOT NULL,
    paid_date date,
    notes text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    member_id integer NOT NULL
);


ALTER TABLE public.contributions_contribution OWNER TO neondb_owner;

--
-- Name: contributions_contribution_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.contributions_contribution ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contributions_contribution_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contributions_monthlypool; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.contributions_monthlypool (
    id bigint NOT NULL,
    month character varying(7) NOT NULL,
    total_expected numeric(10,2) NOT NULL,
    total_collected numeric(10,2) NOT NULL,
    is_complete boolean NOT NULL,
    notes text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    buying_member_id integer
);


ALTER TABLE public.contributions_monthlypool OWNER TO neondb_owner;

--
-- Name: contributions_monthlypool_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.contributions_monthlypool ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contributions_monthlypool_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dividends_dividend; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.dividends_dividend (
    id bigint NOT NULL,
    dividend_per_share numeric(10,2) NOT NULL,
    total_dividend numeric(12,2) NOT NULL,
    ex_date date NOT NULL,
    payment_date date,
    notes text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    stock_id bigint NOT NULL
);


ALTER TABLE public.dividends_dividend OWNER TO neondb_owner;

--
-- Name: dividends_dividend_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.dividends_dividend ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dividends_dividend_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO neondb_owner;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_clockedschedule; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.django_celery_beat_clockedschedule (
    id integer NOT NULL,
    clocked_time timestamp with time zone NOT NULL
);


ALTER TABLE public.django_celery_beat_clockedschedule OWNER TO neondb_owner;

--
-- Name: django_celery_beat_clockedschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.django_celery_beat_clockedschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_clockedschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_crontabschedule; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.django_celery_beat_crontabschedule (
    id integer NOT NULL,
    minute character varying(240) NOT NULL,
    hour character varying(96) NOT NULL,
    day_of_week character varying(64) NOT NULL,
    day_of_month character varying(124) NOT NULL,
    month_of_year character varying(64) NOT NULL,
    timezone character varying(63) NOT NULL
);


ALTER TABLE public.django_celery_beat_crontabschedule OWNER TO neondb_owner;

--
-- Name: django_celery_beat_crontabschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.django_celery_beat_crontabschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_crontabschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_intervalschedule; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.django_celery_beat_intervalschedule (
    id integer NOT NULL,
    every integer NOT NULL,
    period character varying(24) NOT NULL
);


ALTER TABLE public.django_celery_beat_intervalschedule OWNER TO neondb_owner;

--
-- Name: django_celery_beat_intervalschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.django_celery_beat_intervalschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_intervalschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_periodictask; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.django_celery_beat_periodictask (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    task character varying(200) NOT NULL,
    args text NOT NULL,
    kwargs text NOT NULL,
    queue character varying(200),
    exchange character varying(200),
    routing_key character varying(200),
    expires timestamp with time zone,
    enabled boolean NOT NULL,
    last_run_at timestamp with time zone,
    total_run_count integer NOT NULL,
    date_changed timestamp with time zone NOT NULL,
    description text NOT NULL,
    crontab_id integer,
    interval_id integer,
    solar_id integer,
    one_off boolean NOT NULL,
    start_time timestamp with time zone,
    priority integer,
    headers text NOT NULL,
    clocked_id integer,
    expire_seconds integer,
    CONSTRAINT django_celery_beat_periodictask_expire_seconds_check CHECK ((expire_seconds >= 0)),
    CONSTRAINT django_celery_beat_periodictask_priority_check CHECK ((priority >= 0)),
    CONSTRAINT django_celery_beat_periodictask_total_run_count_check CHECK ((total_run_count >= 0))
);


ALTER TABLE public.django_celery_beat_periodictask OWNER TO neondb_owner;

--
-- Name: django_celery_beat_periodictask_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.django_celery_beat_periodictask ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_periodictask_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_periodictasks; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.django_celery_beat_periodictasks (
    ident smallint NOT NULL,
    last_update timestamp with time zone NOT NULL
);


ALTER TABLE public.django_celery_beat_periodictasks OWNER TO neondb_owner;

--
-- Name: django_celery_beat_solarschedule; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.django_celery_beat_solarschedule (
    id integer NOT NULL,
    event character varying(24) NOT NULL,
    latitude numeric(9,6) NOT NULL,
    longitude numeric(9,6) NOT NULL
);


ALTER TABLE public.django_celery_beat_solarschedule OWNER TO neondb_owner;

--
-- Name: django_celery_beat_solarschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.django_celery_beat_solarschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_solarschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO neondb_owner;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO neondb_owner;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO neondb_owner;

--
-- Name: investments_stock; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.investments_stock (
    id bigint NOT NULL,
    symbol character varying(20) NOT NULL,
    name character varying(100) NOT NULL,
    quantity integer NOT NULL,
    buy_price numeric(12,2) NOT NULL,
    brokerage numeric(10,2) NOT NULL,
    buy_date date NOT NULL,
    notes text NOT NULL,
    current_price numeric(12,2) NOT NULL,
    last_price_update timestamp with time zone,
    is_sold boolean NOT NULL,
    sell_price numeric(12,2),
    sell_date date,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT investments_stock_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.investments_stock OWNER TO neondb_owner;

--
-- Name: investments_stock_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.investments_stock ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.investments_stock_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: investments_stockpricehistory; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.investments_stockpricehistory (
    id bigint NOT NULL,
    symbol character varying(20) NOT NULL,
    date date NOT NULL,
    close_price numeric(12,2) NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.investments_stockpricehistory OWNER TO neondb_owner;

--
-- Name: investments_stockpricehistory_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.investments_stockpricehistory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.investments_stockpricehistory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: portfolio_portfoliosnapshot; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.portfolio_portfoliosnapshot (
    id bigint NOT NULL,
    date date NOT NULL,
    total_invested numeric(14,2) NOT NULL,
    total_current_value numeric(14,2) NOT NULL,
    total_profit_loss numeric(14,2) NOT NULL,
    profit_loss_percentage numeric(8,2) NOT NULL,
    total_dividends numeric(14,2) NOT NULL,
    member_count integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT portfolio_portfoliosnapshot_member_count_check CHECK ((member_count >= 0))
);


ALTER TABLE public.portfolio_portfoliosnapshot OWNER TO neondb_owner;

--
-- Name: portfolio_portfoliosnapshot_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.portfolio_portfoliosnapshot ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.portfolio_portfoliosnapshot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_blacklistedtoken; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.token_blacklist_blacklistedtoken (
    id bigint NOT NULL,
    blacklisted_at timestamp with time zone NOT NULL,
    token_id bigint NOT NULL
);


ALTER TABLE public.token_blacklist_blacklistedtoken OWNER TO neondb_owner;

--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.token_blacklist_blacklistedtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_blacklistedtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_outstandingtoken; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.token_blacklist_outstandingtoken (
    id bigint NOT NULL,
    token text NOT NULL,
    created_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    user_id integer,
    jti character varying(255) NOT NULL
);


ALTER TABLE public.token_blacklist_outstandingtoken OWNER TO neondb_owner;

--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.token_blacklist_outstandingtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_outstandingtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: accounts_member; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.accounts_member (password, last_login, is_superuser, id, name, phone, email, role, avatar_color, is_active, is_staff, date_joined, updated_at) FROM stdin;
pbkdf2_sha256$870000$SIIhNvm7Rda1D3IgauZAXx$OCpSMqRBif6tIt1BvhoAdozqcMf0yr6VzTdgXisDugM=	2026-05-02 06:11:01.607585+00	t	1	Alekh (Admin)	9925070999	admin@nanibachat.app	admin	#4F46E5	t	t	2026-05-02 05:46:58.745477+00	2026-05-02 06:09:53.858003+00
pbkdf2_sha256$870000$JBeCg6Hq0qHgzZbCIHINAT$FXSu+tDLoA9mnGKGpr+hTf/CCpX21RZGLTjyuxP45ZY=	\N	f	11	Mayank(R.K.)	9825430551	\N	member	#4F46E5	t	f	2026-05-02 06:15:44.347999+00	2026-05-02 06:15:46.237083+00
pbkdf2_sha256$870000$uXPGceLUfJUk4UvBEZp3M5$Ax9aVKgeGY8g7FeHGc7H4xm7jKG21MgFLhQsfxrZ9yk=	\N	f	12	Mayank(K.G)	9537757877	\N	member	#4F46E5	t	f	2026-05-02 06:16:44.518442+00	2026-05-02 06:16:46.133587+00
pbkdf2_sha256$870000$02NMpU2BURjzvV16x5jCVY$dsa4g7RpKRrGGR19Td3GWnKqC5xwPOyS7VwAuuE+o/M=	\N	f	13	Ujjval	7874470996	\N	admin	#4F46E5	t	f	2026-05-02 06:17:23.140176+00	2026-05-02 06:17:25.032469+00
pbkdf2_sha256$870000$1Eg51fkYEz4wRopbxRRDet$D0YPDM9wy9pWOwyGOJArkM8B1FocW3JQaNFF1X6w4nA=	\N	f	14	Pinkesh(R.K.)	9898782286	\N	member	#4F46E5	t	f	2026-05-02 06:18:08.092065+00	2026-05-02 06:18:09.726076+00
pbkdf2_sha256$870000$C6tw0uJkKqITL4GIt8i3gx$vPkIx3JFVMDpTJR49FpQSOJ6Fr53YGfuB2lCp8RzQsM=	\N	f	16	Pavan	7600458760	\N	member	#4F46E5	t	f	2026-05-02 06:19:12.067883+00	2026-05-02 06:19:14.032315+00
pbkdf2_sha256$870000$DtbJ8uoZc1fhfzPhnJMceQ$xN74mkGGNaxH22mux3suV/6zuDcDiedkmiW/OfRV4cA=	\N	f	17	Arth(bholi)	8758581801	\N	admin	#4F46E5	t	f	2026-05-02 06:20:11.813309+00	2026-05-02 06:20:13.734392+00
pbkdf2_sha256$870000$bLi8hSP715xHTRpnbY6D0l$omDQAXe9bhL4SDXJknjHrjm/iDS3Mzf5pim5/rcVpp4=	\N	f	18	Manch	7359987521	\N	member	#4F46E5	t	f	2026-05-02 06:20:43.180423+00	2026-05-02 06:20:45.124675+00
pbkdf2_sha256$870000$NxFPiiahvEEIsQlQ9njHoq$p1XHAMGNi/Akp0jD6OxB4C6uF4PqZiPqo+ISSvkaPns=	\N	f	15	Prashant	8128676782	\N	member	#4F46E5	t	f	2026-05-02 06:18:44.03099+00	2026-05-02 06:23:06.325675+00
pbkdf2_sha256$870000$wYSvMll2dMb6dDIL7xq8Ix$i/P7PfOqkuQ1yXaGOEVkzeUJieBN9CjHKUKlPiQCrhE=	\N	f	19	Aksh	9427847776	\N	member	#4F46E5	t	f	2026-05-02 06:25:27.24312+00	2026-05-02 06:25:29.032835+00
\.


--
-- Data for Name: accounts_member_groups; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.accounts_member_groups (id, member_id, group_id) FROM stdin;
\.


--
-- Data for Name: accounts_member_user_permissions; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.accounts_member_user_permissions (id, member_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add blacklisted token	6	add_blacklistedtoken
22	Can change blacklisted token	6	change_blacklistedtoken
23	Can delete blacklisted token	6	delete_blacklistedtoken
24	Can view blacklisted token	6	view_blacklistedtoken
25	Can add outstanding token	7	add_outstandingtoken
26	Can change outstanding token	7	change_outstandingtoken
27	Can delete outstanding token	7	delete_outstandingtoken
28	Can view outstanding token	7	view_outstandingtoken
29	Can add crontab	8	add_crontabschedule
30	Can change crontab	8	change_crontabschedule
31	Can delete crontab	8	delete_crontabschedule
32	Can view crontab	8	view_crontabschedule
33	Can add interval	9	add_intervalschedule
34	Can change interval	9	change_intervalschedule
35	Can delete interval	9	delete_intervalschedule
36	Can view interval	9	view_intervalschedule
37	Can add periodic task	10	add_periodictask
38	Can change periodic task	10	change_periodictask
39	Can delete periodic task	10	delete_periodictask
40	Can view periodic task	10	view_periodictask
41	Can add periodic task track	11	add_periodictasks
42	Can change periodic task track	11	change_periodictasks
43	Can delete periodic task track	11	delete_periodictasks
44	Can view periodic task track	11	view_periodictasks
45	Can add solar event	12	add_solarschedule
46	Can change solar event	12	change_solarschedule
47	Can delete solar event	12	delete_solarschedule
48	Can view solar event	12	view_solarschedule
49	Can add clocked	13	add_clockedschedule
50	Can change clocked	13	change_clockedschedule
51	Can delete clocked	13	delete_clockedschedule
52	Can view clocked	13	view_clockedschedule
53	Can add Member	14	add_member
54	Can change Member	14	change_member
55	Can delete Member	14	delete_member
56	Can view Member	14	view_member
57	Can add Stock	15	add_stock
58	Can change Stock	15	change_stock
59	Can delete Stock	15	delete_stock
60	Can view Stock	15	view_stock
61	Can add Price History	16	add_stockpricehistory
62	Can change Price History	16	change_stockpricehistory
63	Can delete Price History	16	delete_stockpricehistory
64	Can view Price History	16	view_stockpricehistory
65	Can add Monthly Pool	17	add_monthlypool
66	Can change Monthly Pool	17	change_monthlypool
67	Can delete Monthly Pool	17	delete_monthlypool
68	Can view Monthly Pool	17	view_monthlypool
69	Can add Contribution	18	add_contribution
70	Can change Contribution	18	change_contribution
71	Can delete Contribution	18	delete_contribution
72	Can view Contribution	18	view_contribution
73	Can add Dividend	19	add_dividend
74	Can change Dividend	19	change_dividend
75	Can delete Dividend	19	delete_dividend
76	Can view Dividend	19	view_dividend
77	Can add Portfolio Snapshot	20	add_portfoliosnapshot
78	Can change Portfolio Snapshot	20	change_portfoliosnapshot
79	Can delete Portfolio Snapshot	20	delete_portfoliosnapshot
80	Can view Portfolio Snapshot	20	view_portfoliosnapshot
\.


--
-- Data for Name: contributions_contribution; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.contributions_contribution (id, month, amount, status, paid_date, notes, created_at, updated_at, member_id) FROM stdin;
61	2026-02	1000.00	paid	2026-05-02		2026-05-02 06:26:15.052316+00	2026-05-02 06:26:19.127804+00	19
62	2026-02	1000.00	paid	2026-05-02		2026-05-02 06:26:15.247408+00	2026-05-02 06:26:22.049549+00	1
63	2026-02	1000.00	paid	2026-05-02		2026-05-02 06:26:15.375989+00	2026-05-02 06:26:24.140127+00	17
65	2026-02	1000.00	paid	2026-05-02		2026-05-02 06:26:15.629675+00	2026-05-02 06:26:26.914884+00	12
64	2026-02	1000.00	paid	2026-05-02		2026-05-02 06:26:15.502686+00	2026-05-02 06:26:27.397345+00	18
70	2026-02	1000.00	paid	2026-05-02		2026-05-02 06:26:16.262607+00	2026-05-02 06:26:30.695727+00	13
69	2026-02	1000.00	paid	2026-05-02		2026-05-02 06:26:16.136289+00	2026-05-02 06:26:30.950143+00	15
68	2026-02	1000.00	paid	2026-05-02		2026-05-02 06:26:16.009528+00	2026-05-02 06:26:31.204295+00	14
67	2026-02	1000.00	paid	2026-05-02		2026-05-02 06:26:15.882831+00	2026-05-02 06:26:31.458481+00	16
66	2026-02	1000.00	paid	2026-05-02		2026-05-02 06:26:15.756215+00	2026-05-02 06:26:31.722358+00	11
71	2026-03	1000.00	paid	2026-05-02		2026-05-02 06:26:56.081291+00	2026-05-02 06:27:04.257951+00	19
93	2026-05	1000.00	paid	2026-05-03		2026-05-03 04:40:46.949555+00	2026-05-03 04:41:05.54377+00	17
76	2026-03	1000.00	paid	2026-05-02		2026-05-02 06:26:56.713622+00	2026-05-02 06:27:08.403418+00	11
75	2026-03	1000.00	paid	2026-05-02		2026-05-02 06:26:56.587196+00	2026-05-02 06:27:08.657512+00	12
74	2026-03	1000.00	paid	2026-05-02		2026-05-02 06:26:56.461165+00	2026-05-02 06:27:08.912259+00	18
80	2026-03	1000.00	paid	2026-05-02		2026-05-02 06:26:57.218911+00	2026-05-02 06:27:14.481258+00	13
79	2026-03	1000.00	paid	2026-05-02		2026-05-02 06:26:57.092645+00	2026-05-02 06:27:14.737004+00	15
78	2026-03	1000.00	paid	2026-05-02		2026-05-02 06:26:56.966319+00	2026-05-02 06:27:14.993257+00	14
77	2026-03	1000.00	paid	2026-05-02		2026-05-02 06:26:56.840058+00	2026-05-02 06:27:15.247423+00	16
92	2026-05	1000.00	paid	2026-05-03		2026-05-03 04:40:46.832148+00	2026-05-03 04:41:29.563979+00	1
97	2026-05	1000.00	paid	2026-05-03		2026-05-03 04:40:47.419274+00	2026-05-03 04:41:37.193949+00	16
96	2026-05	1000.00	paid	2026-05-03		2026-05-03 04:40:47.301489+00	2026-05-03 14:46:14.180268+00	11
98	2026-05	1000.00	paid	2026-05-03		2026-05-03 04:40:47.53635+00	2026-05-03 14:46:18.74601+00	14
99	2026-05	1000.00	paid	2026-05-03		2026-05-03 04:40:47.657299+00	2026-05-03 15:50:24.597317+00	15
94	2026-05	1000.00	paid	2026-05-04		2026-05-03 04:40:47.066809+00	2026-05-04 15:56:45.811028+00	18
100	2026-05	1000.00	paid	2026-05-04		2026-05-03 04:40:47.779635+00	2026-05-04 16:39:46.615206+00	13
81	2026-04	1000.00	paid	2026-05-02		2026-05-02 06:27:40.549869+00	2026-05-02 06:27:55.141772+00	19
84	2026-04	1000.00	paid	2026-05-02		2026-05-02 06:27:40.930745+00	2026-05-02 06:28:01.978785+00	18
85	2026-04	1000.00	paid	2026-05-02		2026-05-02 06:27:41.057533+00	2026-05-02 06:28:05.537447+00	12
86	2026-04	1000.00	paid	2026-05-02		2026-05-02 06:27:41.184071+00	2026-05-02 06:28:09.072623+00	11
87	2026-04	1000.00	paid	2026-05-02		2026-05-02 06:27:41.310479+00	2026-05-02 06:28:09.328732+00	16
88	2026-04	1000.00	paid	2026-05-02		2026-05-02 06:27:41.437165+00	2026-05-02 06:28:09.583334+00	14
89	2026-04	1000.00	paid	2026-05-02		2026-05-02 06:27:41.563637+00	2026-05-02 06:28:09.837679+00	15
90	2026-04	1000.00	paid	2026-05-02		2026-05-02 06:27:41.690188+00	2026-05-02 06:28:33.40137+00	13
73	2026-03	190.00	paid	2026-05-02		2026-05-02 06:26:56.334895+00	2026-05-02 06:29:12.947359+00	17
83	2026-04	1810.00	paid	2026-05-02		2026-05-02 06:27:40.803086+00	2026-05-02 06:29:26.50019+00	17
72	2026-03	1468.00	paid	2026-05-02		2026-05-02 06:26:56.208563+00	2026-05-02 06:30:43.373002+00	1
82	2026-04	540.00	paid	2026-05-02		2026-05-02 06:27:40.676378+00	2026-05-02 06:30:58.700455+00	1
95	2026-05	1000.00	unpaid	\N		2026-05-03 04:40:47.184293+00	2026-05-03 04:40:47.184308+00	12
91	2026-05	1000.00	paid	2026-05-08		2026-05-03 04:40:46.703043+00	2026-05-08 04:16:13.616041+00	19
\.


--
-- Data for Name: contributions_monthlypool; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.contributions_monthlypool (id, month, total_expected, total_collected, is_complete, notes, created_at, buying_member_id) FROM stdin;
\.


--
-- Data for Name: dividends_dividend; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.dividends_dividend (id, dividend_per_share, total_dividend, ex_date, payment_date, notes, created_at, updated_at, stock_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-05-02 06:11:25.939919+00	4	Amit Kumar (9876543212)	3		14	1
2	2026-05-02 06:11:25.939987+00	7	Anita Desai (9876543215)	3		14	1
3	2026-05-02 06:11:25.940008+00	10	Karan Joshi (9876543218)	3		14	1
4	2026-05-02 06:11:25.940023+00	5	Neha Gupta (9876543213)	3		14	1
5	2026-05-02 06:11:25.940037+00	3	Priya Patel (9876543211)	3		14	1
6	2026-05-02 06:11:25.940051+00	2	Rahul Sharma (9876543210)	3		14	1
7	2026-05-02 06:11:25.940065+00	8	Rajesh Mehta (9876543216)	3		14	1
8	2026-05-02 06:11:25.940079+00	9	Sunita Reddy (9876543217)	3		14	1
9	2026-05-02 06:11:25.940092+00	6	Vikram Singh (9876543214)	3		14	1
10	2026-05-02 06:11:56.092142+00	51	Alekh (Admin) - 2026-03 - ₹1000.00 (paid)	3		18	1
11	2026-05-02 06:11:56.092206+00	41	Alekh (Admin) - 2026-02 - ₹1000.00 (paid)	3		18	1
12	2026-05-02 06:11:56.092231+00	31	Alekh (Admin) - 2026-01 - ₹1000.00 (paid)	3		18	1
13	2026-05-02 06:11:56.092253+00	21	Alekh (Admin) - 2025-12 - ₹1000.00 (paid)	3		18	1
14	2026-05-02 06:11:56.092275+00	11	Alekh (Admin) - 2025-11 - ₹1000.00 (paid)	3		18	1
15	2026-05-02 06:11:56.092296+00	1	Alekh (Admin) - 2025-10 - ₹1000.00 (paid)	3		18	1
16	2026-05-02 06:12:08.480645+00	6	2026-03 - ₹6000.00/₹10000.00	3		17	1
17	2026-05-02 06:12:08.480762+00	5	2026-02 - ₹10000.00/₹10000.00	3		17	1
18	2026-05-02 06:12:08.480801+00	4	2026-01 - ₹10000.00/₹10000.00	3		17	1
19	2026-05-02 06:12:08.480832+00	3	2025-12 - ₹10000.00/₹10000.00	3		17	1
20	2026-05-02 06:12:08.480862+00	2	2025-11 - ₹10000.00/₹10000.00	3		17	1
21	2026-05-02 06:12:08.480892+00	1	2025-10 - ₹10000.00/₹10000.00	3		17	1
22	2026-05-02 06:12:40.918285+00	5	Wipro (WIPRO.NS) - 15 shares	3		15	1
23	2026-05-02 06:12:40.918344+00	4	Infosys (INFY.NS) - 10 shares	3		15	1
24	2026-05-02 06:12:40.918367+00	3	HDFC Bank (HDFCBANK.NS) - 12 shares	3		15	1
25	2026-05-02 06:12:40.918387+00	2	Reliance Industries (RELIANCE.NS) - 8 shares	3		15	1
26	2026-05-02 06:12:40.918406+00	1	Tata Consultancy Services (TCS.NS) - 5 shares	3		15	1
27	2026-05-02 06:15:46.305666+00	11	Mayank(R.K.) (9825430551)	1	[{"added": {}}]	14	1
28	2026-05-02 06:16:46.196259+00	12	Mayank(K.G) (9537757877)	1	[{"added": {}}]	14	1
29	2026-05-02 06:17:25.09533+00	13	Ujjval (7874470996)	1	[{"added": {}}]	14	1
30	2026-05-02 06:18:09.788757+00	14	Pinkesh(R.K.) (9898782286)	1	[{"added": {}}]	14	1
31	2026-05-02 06:18:46.490767+00	15	8128676782 (Prashant)	1	[{"added": {}}]	14	1
32	2026-05-02 06:19:14.095065+00	16	Pavan (7600458760)	1	[{"added": {}}]	14	1
33	2026-05-02 06:20:13.797156+00	17	Arth(bholi) (8758581801)	1	[{"added": {}}]	14	1
34	2026-05-02 06:20:45.187494+00	18	Manch (7359987521)	1	[{"added": {}}]	14	1
35	2026-05-02 06:23:06.388377+00	15	Prashant (8128676782)	2	[{"changed": {"fields": ["Phone", "Name"]}}]	14	1
36	2026-05-02 06:25:29.095313+00	19	Aksh (9427847776)	1	[{"added": {}}]	14	1
37	2026-05-02 06:37:44.166639+00	8	Jktyre (JKTYRE.NS) - 24 shares	2	[{"changed": {"fields": ["Notes"]}}]	15	1
38	2026-05-02 06:38:06.409503+00	7	HDFC Bank (HDFCBANK.NS) - 11 shares	2	[{"changed": {"fields": ["Notes"]}}]	15	1
39	2026-05-02 06:38:25.862198+00	6	Hyundai (HYUNDAI.NS) - 5 shares	2	[{"changed": {"fields": ["Notes"]}}]	15	1
\.


--
-- Data for Name: django_celery_beat_clockedschedule; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.django_celery_beat_clockedschedule (id, clocked_time) FROM stdin;
\.


--
-- Data for Name: django_celery_beat_crontabschedule; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.django_celery_beat_crontabschedule (id, minute, hour, day_of_week, day_of_month, month_of_year, timezone) FROM stdin;
\.


--
-- Data for Name: django_celery_beat_intervalschedule; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.django_celery_beat_intervalschedule (id, every, period) FROM stdin;
\.


--
-- Data for Name: django_celery_beat_periodictask; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.django_celery_beat_periodictask (id, name, task, args, kwargs, queue, exchange, routing_key, expires, enabled, last_run_at, total_run_count, date_changed, description, crontab_id, interval_id, solar_id, one_off, start_time, priority, headers, clocked_id, expire_seconds) FROM stdin;
\.


--
-- Data for Name: django_celery_beat_periodictasks; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.django_celery_beat_periodictasks (ident, last_update) FROM stdin;
\.


--
-- Data for Name: django_celery_beat_solarschedule; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.django_celery_beat_solarschedule (id, event, latitude, longitude) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	token_blacklist	blacklistedtoken
7	token_blacklist	outstandingtoken
8	django_celery_beat	crontabschedule
9	django_celery_beat	intervalschedule
10	django_celery_beat	periodictask
11	django_celery_beat	periodictasks
12	django_celery_beat	solarschedule
13	django_celery_beat	clockedschedule
14	accounts	member
15	investments	stock
16	investments	stockpricehistory
17	contributions	monthlypool
18	contributions	contribution
19	dividends	dividend
20	portfolio	portfoliosnapshot
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-05-02 05:46:29.668119+00
2	contenttypes	0002_remove_content_type_name	2026-05-02 05:46:30.016453+00
3	auth	0001_initial	2026-05-02 05:46:31.169231+00
4	auth	0002_alter_permission_name_max_length	2026-05-02 05:46:31.376569+00
5	auth	0003_alter_user_email_max_length	2026-05-02 05:46:31.517117+00
6	auth	0004_alter_user_username_opts	2026-05-02 05:46:31.724396+00
7	auth	0005_alter_user_last_login_null	2026-05-02 05:46:31.933768+00
8	auth	0006_require_contenttypes_0002	2026-05-02 05:46:32.137753+00
9	auth	0007_alter_validators_add_error_messages	2026-05-02 05:46:32.345127+00
10	auth	0008_alter_user_username_max_length	2026-05-02 05:46:32.553345+00
11	auth	0009_alter_user_last_name_max_length	2026-05-02 05:46:32.760156+00
12	auth	0010_alter_group_name_max_length	2026-05-02 05:46:33.107161+00
13	auth	0011_update_proxy_permissions	2026-05-02 05:46:33.247437+00
14	auth	0012_alter_user_first_name_max_length	2026-05-02 05:46:33.456115+00
15	accounts	0001_initial	2026-05-02 05:46:34.85652+00
16	admin	0001_initial	2026-05-02 05:46:35.417763+00
17	admin	0002_logentry_remove_auto_add	2026-05-02 05:46:35.492021+00
18	admin	0003_logentry_add_action_flag_choices	2026-05-02 05:46:35.702929+00
19	contributions	0001_initial	2026-05-02 05:46:36.65149+00
20	investments	0001_initial	2026-05-02 05:46:37.247466+00
21	dividends	0001_initial	2026-05-02 05:46:37.674326+00
22	django_celery_beat	0001_initial	2026-05-02 05:46:38.534807+00
23	django_celery_beat	0002_auto_20161118_0346	2026-05-02 05:46:38.95681+00
24	django_celery_beat	0003_auto_20161209_0049	2026-05-02 05:46:39.167702+00
25	django_celery_beat	0004_auto_20170221_0000	2026-05-02 05:46:39.306952+00
26	django_celery_beat	0005_add_solarschedule_events_choices	2026-05-02 05:46:39.514283+00
27	django_celery_beat	0006_auto_20180322_0932	2026-05-02 05:46:40.165138+00
28	django_celery_beat	0007_auto_20180521_0826	2026-05-02 05:46:40.588975+00
29	django_celery_beat	0008_auto_20180914_1922	2026-05-02 05:46:40.777692+00
30	django_celery_beat	0006_auto_20180210_1226	2026-05-02 05:46:40.999255+00
31	django_celery_beat	0006_periodictask_priority	2026-05-02 05:46:41.359048+00
32	django_celery_beat	0009_periodictask_headers	2026-05-02 05:46:41.706265+00
33	django_celery_beat	0010_auto_20190429_0326	2026-05-02 05:46:42.020699+00
34	django_celery_beat	0011_auto_20190508_0153	2026-05-02 05:46:42.582833+00
35	django_celery_beat	0012_periodictask_expire_seconds	2026-05-02 05:46:42.795342+00
36	django_celery_beat	0013_auto_20200609_0727	2026-05-02 05:46:42.946226+00
37	django_celery_beat	0014_remove_clockedschedule_enabled	2026-05-02 05:46:43.288549+00
38	django_celery_beat	0015_edit_solarschedule_events_choices	2026-05-02 05:46:43.428758+00
39	django_celery_beat	0016_alter_crontabschedule_timezone	2026-05-02 05:46:43.64168+00
40	django_celery_beat	0017_alter_crontabschedule_month_of_year	2026-05-02 05:46:43.867598+00
41	django_celery_beat	0018_improve_crontab_helptext	2026-05-02 05:46:44.077728+00
42	django_celery_beat	0019_alter_periodictasks_options	2026-05-02 05:46:44.283182+00
43	portfolio	0001_initial	2026-05-02 05:46:44.63021+00
44	sessions	0001_initial	2026-05-02 05:46:45.117717+00
45	token_blacklist	0001_initial	2026-05-02 05:46:45.718235+00
46	token_blacklist	0002_outstandingtoken_jti_hex	2026-05-02 05:46:45.931852+00
47	token_blacklist	0003_auto_20171017_2007	2026-05-02 05:46:46.223464+00
48	token_blacklist	0004_auto_20171017_2013	2026-05-02 05:46:46.641866+00
49	token_blacklist	0005_remove_outstandingtoken_jti	2026-05-02 05:46:46.924991+00
50	token_blacklist	0006_auto_20171017_2113	2026-05-02 05:46:47.205352+00
51	token_blacklist	0007_auto_20171017_2214	2026-05-02 05:46:47.883589+00
52	token_blacklist	0008_migrate_to_bigautofield	2026-05-02 05:46:48.909281+00
53	token_blacklist	0010_fix_migrate_to_bigautofield	2026-05-02 05:46:49.056797+00
54	token_blacklist	0011_linearizes_history	2026-05-02 05:46:49.261818+00
55	token_blacklist	0012_alter_outstandingtoken_user	2026-05-02 05:46:49.474084+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
x76mk759nft63a4j4f3zr4ykenmqvi1l	.eJxVjMEOwiAQRP-FsyFgu0I9eu83kN1lkaqBpLQn47_bJj3ocea9mbcKuC45rE3mMEV1VVadfjtCfkrZQXxguVfNtSzzRHpX9EGbHmuU1-1w_w4ytrytkxcjRIhdiiAAAxK4fpBLZ7zvE5szsNhk0botAkQkJkZG1xn2yanPFxBhOR4:1wJ3Z7:YUncfVzjB5uMMSnMV7Li30j-tTU-Vg6f0mpJsBr-QBQ	2026-05-16 06:11:01.67262+00
\.


--
-- Data for Name: investments_stock; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.investments_stock (id, symbol, name, quantity, buy_price, brokerage, buy_date, notes, current_price, last_price_update, is_sold, sell_price, sell_date, created_at, updated_at) FROM stdin;
8	JKTYRE.NS	Jktyre	24	398.75	45.00	2026-04-24	bought In the account of the Mayank(K.g.)	405.95	2026-05-09 12:00:47.233147+00	f	\N	\N	2026-05-02 06:35:28.443568+00	2026-05-02 06:37:44.103004+00
7	HDFCBANK.NS	HDFC Bank	11	876.00	22.00	2026-03-02	bought in the account of the Alekh	780.85	2026-05-09 12:00:47.309573+00	f	\N	\N	2026-05-02 06:34:10.667628+00	2026-05-02 06:38:06.346021+00
6	HYUNDAI.NS	Hyundai	5	2162.00	0.00	2026-02-12	bought in the account of the Bholi	1852.80	2026-05-09 12:00:47.379639+00	f	\N	\N	2026-05-02 06:32:26.348099+00	2026-05-02 06:38:25.798438+00
\.


--
-- Data for Name: investments_stockpricehistory; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.investments_stockpricehistory (id, symbol, date, close_price, created_at) FROM stdin;
\.


--
-- Data for Name: portfolio_portfoliosnapshot; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.portfolio_portfoliosnapshot (id, date, total_invested, total_current_value, total_profit_loss, profit_loss_percentage, total_dividends, member_count, created_at) FROM stdin;
1	2026-02-01	40000.00	40000.00	0.00	0.00	555.00	10	2026-05-02 05:47:24.066385+00
2	2026-02-02	40200.00	40207.21	7.21	0.02	560.00	10	2026-05-02 05:47:24.321292+00
3	2026-02-03	40400.00	40383.49	-16.51	-0.04	565.00	10	2026-05-02 05:47:24.571054+00
4	2026-02-04	40600.00	40607.78	7.78	0.02	570.00	10	2026-05-02 05:47:24.821359+00
5	2026-02-05	40800.00	40860.71	60.71	0.15	575.00	10	2026-05-02 05:47:25.071191+00
6	2026-02-06	41000.00	40997.96	-2.04	0.00	580.00	10	2026-05-02 05:47:25.320431+00
7	2026-02-07	41200.00	41186.62	-13.38	-0.03	585.00	10	2026-05-02 05:47:25.569775+00
8	2026-02-08	41400.00	41509.30	109.30	0.26	590.00	10	2026-05-02 05:47:25.819089+00
9	2026-02-09	41600.00	41619.63	19.63	0.05	595.00	10	2026-05-02 05:47:26.068804+00
10	2026-02-10	41800.00	41806.12	6.12	0.01	600.00	10	2026-05-02 05:47:26.318347+00
11	2026-02-11	42000.00	42070.04	70.04	0.17	605.00	10	2026-05-02 05:47:26.567727+00
12	2026-02-12	42200.00	42242.09	42.09	0.10	610.00	10	2026-05-02 05:47:26.817561+00
13	2026-02-13	42400.00	42295.13	-104.87	-0.25	615.00	10	2026-05-02 05:47:27.067844+00
14	2026-02-14	42600.00	42680.06	80.06	0.19	620.00	10	2026-05-02 05:47:27.317757+00
15	2026-02-15	42800.00	43003.39	203.39	0.48	625.00	10	2026-05-02 05:47:27.571893+00
16	2026-02-16	43000.00	43186.74	186.74	0.43	630.00	10	2026-05-02 05:47:27.821975+00
17	2026-02-17	43200.00	43289.55	89.55	0.21	635.00	10	2026-05-02 05:47:28.071805+00
18	2026-02-18	43400.00	43488.26	88.26	0.20	640.00	10	2026-05-02 05:47:28.333951+00
19	2026-02-19	43600.00	43530.75	-69.25	-0.16	645.00	10	2026-05-02 05:47:28.583708+00
20	2026-02-20	43800.00	43926.11	126.11	0.29	650.00	10	2026-05-02 05:47:28.836453+00
21	2026-02-21	44000.00	44042.54	42.54	0.10	655.00	10	2026-05-02 05:47:29.08636+00
22	2026-02-22	44200.00	44223.18	23.18	0.05	660.00	10	2026-05-02 05:47:29.336384+00
23	2026-02-23	44400.00	44543.61	143.61	0.32	665.00	10	2026-05-02 05:47:29.589075+00
24	2026-02-24	44600.00	44963.29	363.29	0.81	670.00	10	2026-05-02 05:47:29.839119+00
25	2026-02-25	44800.00	45112.63	312.63	0.70	675.00	10	2026-05-02 05:47:30.098714+00
26	2026-02-26	45000.00	45385.57	385.57	0.86	680.00	10	2026-05-02 05:47:30.349479+00
27	2026-02-27	45200.00	45689.28	489.28	1.08	685.00	10	2026-05-02 05:47:30.605918+00
28	2026-02-28	45400.00	45677.37	277.37	0.61	690.00	10	2026-05-02 05:47:30.855802+00
29	2026-03-01	45600.00	46045.82	445.82	0.98	695.00	10	2026-05-02 05:47:31.105495+00
30	2026-03-02	45800.00	45676.83	-123.17	-0.27	700.00	10	2026-05-02 05:47:31.356689+00
31	2026-03-03	46000.00	46002.01	2.01	0.00	705.00	10	2026-05-02 05:47:31.607003+00
32	2026-03-04	46200.00	46353.06	153.06	0.33	710.00	10	2026-05-02 05:47:31.857537+00
33	2026-03-05	46400.00	46876.13	476.13	1.03	715.00	10	2026-05-02 05:47:32.107605+00
34	2026-03-06	46600.00	46680.56	80.56	0.17	720.00	10	2026-05-02 05:47:32.363984+00
35	2026-03-07	46800.00	47261.57	461.57	0.99	725.00	10	2026-05-02 05:47:32.613685+00
36	2026-03-08	47000.00	46711.52	-288.48	-0.61	730.00	10	2026-05-02 05:47:32.864874+00
37	2026-03-09	47200.00	47738.09	538.09	1.14	735.00	10	2026-05-02 05:47:33.115482+00
38	2026-03-10	47400.00	47343.96	-56.04	-0.12	740.00	10	2026-05-02 05:47:33.381735+00
39	2026-03-11	47600.00	48275.37	675.37	1.42	745.00	10	2026-05-02 05:47:33.634263+00
40	2026-03-12	47800.00	48005.80	205.80	0.43	750.00	10	2026-05-02 05:47:33.883842+00
41	2026-03-13	48000.00	48515.12	515.12	1.07	755.00	10	2026-05-02 05:47:34.134017+00
42	2026-03-14	48200.00	48712.51	512.51	1.06	760.00	10	2026-05-02 05:47:34.384217+00
43	2026-03-15	48400.00	48310.63	-89.37	-0.18	765.00	10	2026-05-02 05:47:34.634384+00
44	2026-03-16	48600.00	48687.03	87.03	0.18	770.00	10	2026-05-02 05:47:34.886984+00
45	2026-03-17	48800.00	49355.42	555.42	1.14	775.00	10	2026-05-02 05:47:35.148602+00
46	2026-03-18	49000.00	49057.29	57.29	0.12	780.00	10	2026-05-02 05:47:35.398804+00
47	2026-03-19	49200.00	50158.43	958.43	1.95	785.00	10	2026-05-02 05:47:35.649097+00
48	2026-03-20	49400.00	49382.04	-17.96	-0.04	790.00	10	2026-05-02 05:47:35.899522+00
49	2026-03-21	49600.00	49763.49	163.49	0.33	795.00	10	2026-05-02 05:47:36.164045+00
50	2026-03-22	49800.00	49341.28	-458.72	-0.92	800.00	10	2026-05-02 05:47:36.415594+00
51	2026-03-23	50000.00	50120.23	120.23	0.24	805.00	10	2026-05-02 05:47:36.666031+00
52	2026-03-24	50200.00	50844.67	644.67	1.28	810.00	10	2026-05-02 05:47:36.916956+00
53	2026-03-25	50400.00	51433.72	1033.72	2.05	815.00	10	2026-05-02 05:47:37.16775+00
54	2026-03-26	50600.00	51461.07	861.07	1.70	820.00	10	2026-05-02 05:47:37.418001+00
55	2026-03-27	50800.00	50660.56	-139.44	-0.27	825.00	10	2026-05-02 05:47:37.667944+00
56	2026-03-28	51000.00	51386.77	386.77	0.76	830.00	10	2026-05-02 05:47:37.923564+00
57	2026-03-29	51200.00	52151.04	951.04	1.86	835.00	10	2026-05-02 05:47:38.175468+00
58	2026-03-30	51400.00	52270.10	870.10	1.69	840.00	10	2026-05-02 05:47:38.425535+00
59	2026-03-31	51600.00	52005.41	405.41	0.79	845.00	10	2026-05-02 05:47:38.688452+00
60	2026-04-01	51800.00	51293.78	-506.22	-0.98	850.00	10	2026-05-02 05:47:38.942131+00
61	2026-04-02	52000.00	52635.88	635.88	1.22	855.00	10	2026-05-02 05:47:39.192387+00
62	2026-04-03	52200.00	52626.95	426.95	0.82	860.00	10	2026-05-02 05:47:39.442572+00
63	2026-04-04	52400.00	52860.75	460.75	0.88	865.00	10	2026-05-02 05:47:39.709731+00
64	2026-04-05	52600.00	52510.27	-89.73	-0.17	870.00	10	2026-05-02 05:47:39.959407+00
65	2026-04-06	52800.00	53001.13	201.13	0.38	875.00	10	2026-05-02 05:47:40.216187+00
66	2026-04-07	53000.00	54050.85	1050.85	1.98	880.00	10	2026-05-02 05:47:40.467451+00
67	2026-04-08	53200.00	54162.84	962.84	1.81	885.00	10	2026-05-02 05:47:40.719687+00
68	2026-04-09	53400.00	53358.73	-41.27	-0.08	890.00	10	2026-05-02 05:47:40.980733+00
69	2026-04-10	53600.00	54217.92	617.92	1.15	895.00	10	2026-05-02 05:47:41.230945+00
70	2026-04-11	53800.00	53406.10	-393.90	-0.73	900.00	10	2026-05-02 05:47:41.481282+00
71	2026-04-12	54000.00	53579.06	-420.94	-0.78	905.00	10	2026-05-02 05:47:41.731426+00
72	2026-04-13	54200.00	55321.84	1121.84	2.07	910.00	10	2026-05-02 05:47:41.981332+00
73	2026-04-14	54400.00	54551.27	151.27	0.28	915.00	10	2026-05-02 05:47:42.243707+00
74	2026-04-15	54600.00	55513.88	913.88	1.67	920.00	10	2026-05-02 05:47:42.497309+00
75	2026-04-16	54800.00	54101.97	-698.03	-1.27	925.00	10	2026-05-02 05:47:42.750314+00
76	2026-04-17	55000.00	55923.11	923.11	1.68	930.00	10	2026-05-02 05:47:43.000457+00
77	2026-04-18	55200.00	55623.52	423.52	0.77	935.00	10	2026-05-02 05:47:43.250432+00
78	2026-04-19	55400.00	56210.61	810.61	1.46	940.00	10	2026-05-02 05:47:43.509505+00
79	2026-04-20	55600.00	57294.78	1694.78	3.05	945.00	10	2026-05-02 05:47:43.759319+00
80	2026-04-21	55800.00	57347.86	1547.86	2.77	950.00	10	2026-05-02 05:47:44.008853+00
81	2026-04-22	56000.00	56786.39	786.39	1.40	955.00	10	2026-05-02 05:47:44.260311+00
82	2026-04-23	56200.00	55968.52	-231.48	-0.41	960.00	10	2026-05-02 05:47:44.511043+00
83	2026-04-24	56400.00	56365.07	-34.93	-0.06	965.00	10	2026-05-02 05:47:44.763402+00
84	2026-04-25	56600.00	57301.97	701.97	1.24	970.00	10	2026-05-02 05:47:45.016081+00
85	2026-04-26	56800.00	55961.97	-838.03	-1.48	975.00	10	2026-05-02 05:47:45.266585+00
86	2026-04-27	57000.00	57811.87	811.87	1.42	980.00	10	2026-05-02 05:47:45.516722+00
87	2026-04-28	57200.00	56986.43	-213.57	-0.37	985.00	10	2026-05-02 05:47:45.767531+00
88	2026-04-29	57400.00	56563.88	-836.12	-1.46	990.00	10	2026-05-02 05:47:46.021956+00
89	2026-04-30	57600.00	56902.70	-697.30	-1.21	995.00	10	2026-05-02 05:47:46.273517+00
90	2026-05-01	57800.00	59948.61	2148.61	3.72	1000.00	10	2026-05-02 05:47:46.523726+00
\.


--
-- Data for Name: token_blacklist_blacklistedtoken; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.token_blacklist_blacklistedtoken (id, blacklisted_at, token_id) FROM stdin;
1	2026-05-02 08:02:51.72665+00	1
2	2026-05-03 03:51:24.737062+00	3
3	2026-05-03 04:39:46.775696+00	2
4	2026-05-04 15:55:55.389968+00	4
5	2026-05-04 16:54:33.051463+00	5
6	2026-05-05 14:09:56.708969+00	9
7	2026-05-06 04:28:44.880815+00	8
8	2026-05-06 06:58:05.751374+00	7
9	2026-05-07 03:51:39.177619+00	6
10	2026-05-08 03:41:50.077563+00	14
11	2026-05-08 04:49:25.495387+00	11
\.


--
-- Data for Name: token_blacklist_outstandingtoken; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.token_blacklist_outstandingtoken (id, token, created_at, expires_at, user_id, jti) FROM stdin;
1	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MDI5NDM4OCwiaWF0IjoxNzc3NzAyMzg4LCJqdGkiOiJhZWVhNDY5NTgyZDk0MTlmOWNmOTRiNGEzY2NlMzA5MiIsInVzZXJfaWQiOjF9._f0w2RoX5pLNjLQaokr5si7EH_kWaOIxqxn1rOA6EuU	2026-05-02 06:13:08.034884+00	2026-06-01 06:13:08+00	1	aeea469582d9419f9cf94b4a3cce3092
2	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MDMwMDk3NSwiaWF0IjoxNzc3NzA4OTc1LCJqdGkiOiI0MWFmZmY5OGM2Mjk0NzYyOWQzOTNlZWJhZTY5NGNlYiIsInVzZXJfaWQiOjF9.1zDzqJe46bX6oIMqgJuUfKOQHE1X4RfcaxyGHP9Jd4M	2026-05-02 08:02:55.828376+00	2026-06-01 08:02:55+00	1	41afff98c62947629d393eebae694ceb
3	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MDEyMTY1MSwiaWF0IjoxNzc3NTI5NjUxLCJqdGkiOiJhM2UzMTk4NjkzMWU0ODJmODg5NmRhODcwOGRmYWUwYyIsInVzZXJfaWQiOjE3LCJuYW1lIjoiUGF2YW4iLCJyb2xlIjoibWVtYmVyIiwicGhvbmUiOiI3NjAwNDU4NzYwIn0.3p1HxEF1IBZo3MO8sXkl9VabksvSTyODWbQod8AaG_k	2026-05-03 03:51:23.05934+00	2026-05-30 06:14:11+00	17	a3e31986931e482f8896da8708dfae0c
4	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MDQ0OTY0MiwiaWF0IjoxNzc3ODU3NjQyLCJqdGkiOiI3Y2M5ZDY4NzdkZmM0NTFhOGRlOTFmMzEyZTUzNjE0YyIsInVzZXJfaWQiOjF9.7QtBwKFDq1LfPoT6ZbyqsaQOddlgdMtS-pxrLtEjaKc	2026-05-04 01:20:42.634375+00	2026-06-03 01:20:42+00	1	7cc9d6877dfc451a8de91f312e53614c
5	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MDQ2MDIxNywiaWF0IjoxNzc3ODY4MjE3LCJqdGkiOiJlODYwYWZlNjE4ZmM0YWRlODM1YTk2MzkxMTkzZDA1MSIsInVzZXJfaWQiOjE2fQ.xOHfsrIZIrvtRh9a4TkK_mp_0usFjTcKj69LXQzp2EE	2026-05-04 04:16:57.230847+00	2026-06-03 04:16:57+00	16	e860afe618fc4ade835a96391193d051
6	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MDQ2MzQ0OCwiaWF0IjoxNzc3ODcxNDQ4LCJqdGkiOiIzNjUyNDRhZGEzMmU0MzBlYTEzZWViM2Y3MWVkY2FkZCIsInVzZXJfaWQiOjEyfQ.tOjRNjxel-5F7gcNq9ww-pAzsHiKoKef9q-H89DO750	2026-05-04 05:10:48.031772+00	2026-06-03 05:10:48+00	12	365244ada32e430ea13eeb3f71edcadd
7	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MDU0OTg3NiwiaWF0IjoxNzc3OTU3ODc2LCJqdGkiOiI0MzE5OWU1NzMxZGE0NjNiOWMyZWJmMzQ3NmFhOTYzOSIsInVzZXJfaWQiOjE2fQ.AtvcCeldOnkKG4JYc9m7xuzY9ZMwxMjyIvpwRGWXq2k	2026-05-05 05:11:16.323735+00	2026-06-04 05:11:16+00	16	43199e5731da463b9c2ebf3476aa9639
8	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MDU1MTI0MCwiaWF0IjoxNzc3OTU5MjQwLCJqdGkiOiI4NjI0NTVmMTAzNDU0OGU2OGNmY2IzNzRlYmE5ZjhmMiIsInVzZXJfaWQiOjF9.UqY4hmwsyiLTQnL60Xinigx_VOdi5pDUENIcs20R-Vw	2026-05-05 05:34:00.829674+00	2026-06-04 05:34:00+00	1	862455f1034548e68cfcb374eba9f8f2
9	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3OTYzMjQ0NywiaWF0IjoxNzc3MDQwNDQ3LCJqdGkiOiJlMDYxMzZjYTNkZGE0NzEzOWJmNzcwZjU2ODYzNGFkZiIsInVzZXJfaWQiOjEzLCJuYW1lIjoiQWtzaCIsInJvbGUiOiJtZW1iZXIiLCJwaG9uZSI6Ijk0Mjc4NDc3NzYifQ.cVVOkMNInwlTX8ft1ZTicdNF3azeGPEkLmOW7oiCMOo	2026-05-05 14:09:55.020889+00	2026-05-24 14:20:47+00	13	e06136ca3dda47139bf770f568634adf
10	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MDY2MjU3MywiaWF0IjoxNzc4MDcwNTczLCJqdGkiOiJkNjU0YWE2ODY3YmU0NGU1OTI0NjU3ZDBjMWQwNjVmNCIsInVzZXJfaWQiOjE0fQ.a_DlXPVk3YSitVPCzTuVsOZcV_vCnHKFpIl76WRE7WI	2026-05-06 12:29:33.423969+00	2026-06-05 12:29:33+00	14	d654aa6867be44e5924657d0c1d065f4
11	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MDcxNzcwMSwiaWF0IjoxNzc4MTI1NzAxLCJqdGkiOiJlZWUyN2VjNDk2ZWU0Y2I0OThjZjZkZjJjNWI1ZjkxNyIsInVzZXJfaWQiOjE2fQ.thWOxv-bgGrRA2Dq5unugQuPT0V2wdmZgLRGs0yEwRQ	2026-05-07 03:48:21.434415+00	2026-06-06 03:48:21+00	16	eee27ec496ee4cb498cf6df2c5b5f917
12	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MDcyMTc1MSwiaWF0IjoxNzc4MTI5NzUxLCJqdGkiOiI3ZjlhNGE3YThmYzk0Nzg5OTNiY2JmODMyNmJiYTQyYiIsInVzZXJfaWQiOjE5fQ.oSSQcnDce3Wg8JSlP_zZeQPaFxFWKd_EN1WCv_JEd04	2026-05-07 04:55:51.328257+00	2026-06-06 04:55:51+00	19	7f9a4a7a8fc9478993bcbf8326bba42b
13	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MDczMjEzMiwiaWF0IjoxNzc4MTQwMTMyLCJqdGkiOiI3ODI5YzJlOTE2MjI0N2FkYjEzN2M3OTY0ZTgzNjU4MiIsInVzZXJfaWQiOjF9.dWV8HTbJrMmDYuDN5m4hDVXfh32hizS0LxE6tFlSEs0	2026-05-07 07:48:52.223526+00	2026-06-06 07:48:52+00	1	7829c2e9162247adb137c7964e836582
14	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MDczMjIzOCwiaWF0IjoxNzc4MTQwMjM4LCJqdGkiOiI2NmM3OTM0YmE2NzA0YzJhYmMwM2M1MTg2M2Y3OTRiYSIsInVzZXJfaWQiOjF9.lurL7n69wy_vaqnnkt58E2Jv-bQbRMe8Nj4thR-I6_M	2026-05-07 07:50:38.130266+00	2026-06-06 07:50:38+00	1	66c7934ba6704c2abc03c51863f794ba
15	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MDkyMDAzOCwiaWF0IjoxNzc4MzI4MDM4LCJqdGkiOiJkYzk2MTMxMzY3ZDE0OGNmYTVmNjAxYTlhOTA0MWZiMCIsInVzZXJfaWQiOjF9.8WVBreyCbC_AwlSQ6T5RUT6cDgQ3E9U7AvR43aMD_RA	2026-05-09 12:00:38.236853+00	2026-06-08 12:00:38+00	1	dc96131367d148cfa5f601a9a9041fb0
\.


--
-- Name: accounts_member_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.accounts_member_groups_id_seq', 1, false);


--
-- Name: accounts_member_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.accounts_member_id_seq', 19, true);


--
-- Name: accounts_member_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.accounts_member_user_permissions_id_seq', 1, false);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 80, true);


--
-- Name: contributions_contribution_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.contributions_contribution_id_seq', 100, true);


--
-- Name: contributions_monthlypool_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.contributions_monthlypool_id_seq', 6, true);


--
-- Name: dividends_dividend_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.dividends_dividend_id_seq', 3, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 39, true);


--
-- Name: django_celery_beat_clockedschedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.django_celery_beat_clockedschedule_id_seq', 1, false);


--
-- Name: django_celery_beat_crontabschedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.django_celery_beat_crontabschedule_id_seq', 1, false);


--
-- Name: django_celery_beat_intervalschedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.django_celery_beat_intervalschedule_id_seq', 1, false);


--
-- Name: django_celery_beat_periodictask_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.django_celery_beat_periodictask_id_seq', 1, false);


--
-- Name: django_celery_beat_solarschedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.django_celery_beat_solarschedule_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 20, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 55, true);


--
-- Name: investments_stock_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.investments_stock_id_seq', 8, true);


--
-- Name: investments_stockpricehistory_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.investments_stockpricehistory_id_seq', 1, false);


--
-- Name: portfolio_portfoliosnapshot_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.portfolio_portfoliosnapshot_id_seq', 90, true);


--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.token_blacklist_blacklistedtoken_id_seq', 11, true);


--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.token_blacklist_outstandingtoken_id_seq', 15, true);


--
-- Name: accounts_member accounts_member_email_key; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.accounts_member
    ADD CONSTRAINT accounts_member_email_key UNIQUE (email);


--
-- Name: accounts_member_groups accounts_member_groups_member_id_group_id_c77bff9c_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.accounts_member_groups
    ADD CONSTRAINT accounts_member_groups_member_id_group_id_c77bff9c_uniq UNIQUE (member_id, group_id);


--
-- Name: accounts_member_groups accounts_member_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.accounts_member_groups
    ADD CONSTRAINT accounts_member_groups_pkey PRIMARY KEY (id);


--
-- Name: accounts_member accounts_member_phone_key; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.accounts_member
    ADD CONSTRAINT accounts_member_phone_key UNIQUE (phone);


--
-- Name: accounts_member accounts_member_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.accounts_member
    ADD CONSTRAINT accounts_member_pkey PRIMARY KEY (id);


--
-- Name: accounts_member_user_permissions accounts_member_user_per_member_id_permission_id_0ae3c3ea_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.accounts_member_user_permissions
    ADD CONSTRAINT accounts_member_user_per_member_id_permission_id_0ae3c3ea_uniq UNIQUE (member_id, permission_id);


--
-- Name: accounts_member_user_permissions accounts_member_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.accounts_member_user_permissions
    ADD CONSTRAINT accounts_member_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: contributions_contribution contributions_contribution_member_id_month_a7c1fe39_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.contributions_contribution
    ADD CONSTRAINT contributions_contribution_member_id_month_a7c1fe39_uniq UNIQUE (member_id, month);


--
-- Name: contributions_contribution contributions_contribution_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.contributions_contribution
    ADD CONSTRAINT contributions_contribution_pkey PRIMARY KEY (id);


--
-- Name: contributions_monthlypool contributions_monthlypool_month_key; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.contributions_monthlypool
    ADD CONSTRAINT contributions_monthlypool_month_key UNIQUE (month);


--
-- Name: contributions_monthlypool contributions_monthlypool_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.contributions_monthlypool
    ADD CONSTRAINT contributions_monthlypool_pkey PRIMARY KEY (id);


--
-- Name: dividends_dividend dividends_dividend_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.dividends_dividend
    ADD CONSTRAINT dividends_dividend_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_clockedschedule django_celery_beat_clockedschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_celery_beat_clockedschedule
    ADD CONSTRAINT django_celery_beat_clockedschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_crontabschedule django_celery_beat_crontabschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_celery_beat_crontabschedule
    ADD CONSTRAINT django_celery_beat_crontabschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_intervalschedule django_celery_beat_intervalschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_celery_beat_intervalschedule
    ADD CONSTRAINT django_celery_beat_intervalschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_periodictask django_celery_beat_periodictask_name_key; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_periodictask_name_key UNIQUE (name);


--
-- Name: django_celery_beat_periodictask django_celery_beat_periodictask_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_periodictask_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_periodictasks django_celery_beat_periodictasks_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_celery_beat_periodictasks
    ADD CONSTRAINT django_celery_beat_periodictasks_pkey PRIMARY KEY (ident);


--
-- Name: django_celery_beat_solarschedule django_celery_beat_solar_event_latitude_longitude_ba64999a_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_celery_beat_solarschedule
    ADD CONSTRAINT django_celery_beat_solar_event_latitude_longitude_ba64999a_uniq UNIQUE (event, latitude, longitude);


--
-- Name: django_celery_beat_solarschedule django_celery_beat_solarschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_celery_beat_solarschedule
    ADD CONSTRAINT django_celery_beat_solarschedule_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: investments_stock investments_stock_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.investments_stock
    ADD CONSTRAINT investments_stock_pkey PRIMARY KEY (id);


--
-- Name: investments_stockpricehistory investments_stockpricehistory_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.investments_stockpricehistory
    ADD CONSTRAINT investments_stockpricehistory_pkey PRIMARY KEY (id);


--
-- Name: investments_stockpricehistory investments_stockpricehistory_symbol_date_710193f0_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.investments_stockpricehistory
    ADD CONSTRAINT investments_stockpricehistory_symbol_date_710193f0_uniq UNIQUE (symbol, date);


--
-- Name: portfolio_portfoliosnapshot portfolio_portfoliosnapshot_date_key; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.portfolio_portfoliosnapshot
    ADD CONSTRAINT portfolio_portfoliosnapshot_date_key UNIQUE (date);


--
-- Name: portfolio_portfoliosnapshot portfolio_portfoliosnapshot_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.portfolio_portfoliosnapshot
    ADD CONSTRAINT portfolio_portfoliosnapshot_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_key; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_key UNIQUE (token_id);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq UNIQUE (jti);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_pkey PRIMARY KEY (id);


--
-- Name: accounts_member_email_c12225e9_like; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX accounts_member_email_c12225e9_like ON public.accounts_member USING btree (email varchar_pattern_ops);


--
-- Name: accounts_member_groups_group_id_5c4b2fbe; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX accounts_member_groups_group_id_5c4b2fbe ON public.accounts_member_groups USING btree (group_id);


--
-- Name: accounts_member_groups_member_id_e68138f6; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX accounts_member_groups_member_id_e68138f6 ON public.accounts_member_groups USING btree (member_id);


--
-- Name: accounts_member_phone_8574165a_like; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX accounts_member_phone_8574165a_like ON public.accounts_member USING btree (phone varchar_pattern_ops);


--
-- Name: accounts_member_user_permissions_member_id_dded25fd; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX accounts_member_user_permissions_member_id_dded25fd ON public.accounts_member_user_permissions USING btree (member_id);


--
-- Name: accounts_member_user_permissions_permission_id_1dd5f43a; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX accounts_member_user_permissions_permission_id_1dd5f43a ON public.accounts_member_user_permissions USING btree (permission_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: contributions_contribution_member_id_87c35e81; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX contributions_contribution_member_id_87c35e81 ON public.contributions_contribution USING btree (member_id);


--
-- Name: contributions_monthlypool_buying_member_id_73fb1133; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX contributions_monthlypool_buying_member_id_73fb1133 ON public.contributions_monthlypool USING btree (buying_member_id);


--
-- Name: contributions_monthlypool_month_a62792b1_like; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX contributions_monthlypool_month_a62792b1_like ON public.contributions_monthlypool USING btree (month varchar_pattern_ops);


--
-- Name: dividends_dividend_stock_id_ad7011ed; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX dividends_dividend_stock_id_ad7011ed ON public.dividends_dividend USING btree (stock_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_celery_beat_periodictask_clocked_id_47a69f82; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX django_celery_beat_periodictask_clocked_id_47a69f82 ON public.django_celery_beat_periodictask USING btree (clocked_id);


--
-- Name: django_celery_beat_periodictask_crontab_id_d3cba168; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX django_celery_beat_periodictask_crontab_id_d3cba168 ON public.django_celery_beat_periodictask USING btree (crontab_id);


--
-- Name: django_celery_beat_periodictask_interval_id_a8ca27da; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX django_celery_beat_periodictask_interval_id_a8ca27da ON public.django_celery_beat_periodictask USING btree (interval_id);


--
-- Name: django_celery_beat_periodictask_name_265a36b7_like; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX django_celery_beat_periodictask_name_265a36b7_like ON public.django_celery_beat_periodictask USING btree (name varchar_pattern_ops);


--
-- Name: django_celery_beat_periodictask_solar_id_a87ce72c; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX django_celery_beat_periodictask_solar_id_a87ce72c ON public.django_celery_beat_periodictask USING btree (solar_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: investments_stockpricehistory_symbol_3dcf8a38; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX investments_stockpricehistory_symbol_3dcf8a38 ON public.investments_stockpricehistory USING btree (symbol);


--
-- Name: investments_stockpricehistory_symbol_3dcf8a38_like; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX investments_stockpricehistory_symbol_3dcf8a38_like ON public.investments_stockpricehistory USING btree (symbol varchar_pattern_ops);


--
-- Name: token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like ON public.token_blacklist_outstandingtoken USING btree (jti varchar_pattern_ops);


--
-- Name: token_blacklist_outstandingtoken_user_id_83bc629a; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX token_blacklist_outstandingtoken_user_id_83bc629a ON public.token_blacklist_outstandingtoken USING btree (user_id);


--
-- Name: accounts_member_groups accounts_member_groups_group_id_5c4b2fbe_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.accounts_member_groups
    ADD CONSTRAINT accounts_member_groups_group_id_5c4b2fbe_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_member_groups accounts_member_groups_member_id_e68138f6_fk_accounts_member_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.accounts_member_groups
    ADD CONSTRAINT accounts_member_groups_member_id_e68138f6_fk_accounts_member_id FOREIGN KEY (member_id) REFERENCES public.accounts_member(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_member_user_permissions accounts_member_user_member_id_dded25fd_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.accounts_member_user_permissions
    ADD CONSTRAINT accounts_member_user_member_id_dded25fd_fk_accounts_ FOREIGN KEY (member_id) REFERENCES public.accounts_member(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_member_user_permissions accounts_member_user_permission_id_1dd5f43a_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.accounts_member_user_permissions
    ADD CONSTRAINT accounts_member_user_permission_id_1dd5f43a_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contributions_contribution contributions_contri_member_id_87c35e81_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.contributions_contribution
    ADD CONSTRAINT contributions_contri_member_id_87c35e81_fk_accounts_ FOREIGN KEY (member_id) REFERENCES public.accounts_member(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contributions_monthlypool contributions_monthl_buying_member_id_73fb1133_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.contributions_monthlypool
    ADD CONSTRAINT contributions_monthl_buying_member_id_73fb1133_fk_accounts_ FOREIGN KEY (buying_member_id) REFERENCES public.accounts_member(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dividends_dividend dividends_dividend_stock_id_ad7011ed_fk_investments_stock_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.dividends_dividend
    ADD CONSTRAINT dividends_dividend_stock_id_ad7011ed_fk_investments_stock_id FOREIGN KEY (stock_id) REFERENCES public.investments_stock(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_accounts_member_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_member_id FOREIGN KEY (user_id) REFERENCES public.accounts_member(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_clocked_id_47a69f82_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_clocked_id_47a69f82_fk_django_ce FOREIGN KEY (clocked_id) REFERENCES public.django_celery_beat_clockedschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_crontab_id_d3cba168_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_crontab_id_d3cba168_fk_django_ce FOREIGN KEY (crontab_id) REFERENCES public.django_celery_beat_crontabschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_interval_id_a8ca27da_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_interval_id_a8ca27da_fk_django_ce FOREIGN KEY (interval_id) REFERENCES public.django_celery_beat_intervalschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_solar_id_a87ce72c_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_solar_id_a87ce72c_fk_django_ce FOREIGN KEY (solar_id) REFERENCES public.django_celery_beat_solarschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk FOREIGN KEY (token_id) REFERENCES public.token_blacklist_outstandingtoken(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outs_user_id_83bc629a_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outs_user_id_83bc629a_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_member(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: cloud_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE cloud_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO neon_superuser WITH GRANT OPTION;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: cloud_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE cloud_admin IN SCHEMA public GRANT ALL ON TABLES TO neon_superuser WITH GRANT OPTION;


--
-- PostgreSQL database dump complete
--

\unrestrict 6sMHHmxunKIjLQUeQbXNjyfM1chNIHv55Gy9uUVjEONDbfsVV2RPoElwtsnWwD6

