# Generated by Django 5.1.4 on 2026-03-06 13:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_invested', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_current_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_profit_loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('profit_loss_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('total_dividends', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Portfolio Snapshot',
                'verbose_name_plural': 'Portfolio Snapshots',
                'ordering': ['-date'],
            },
        ),
    ]
