# Generated by Django 5.1.4 on 2026-03-06 13:30

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='NSE symbol with .NS suffix (e.g., TCS.NS)', max_length=20)),
                ('name', models.CharField(help_text='Company name', max_length=100)),
                ('quantity', models.PositiveIntegerField(help_text='Number of shares purchased', validators=[django.core.validators.MinValueValidator(1)])),
                ('buy_price', models.DecimalField(decimal_places=2, help_text='Price per share at purchase', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('brokerage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Brokerage/commission paid', max_digits=10)),
                ('buy_date', models.DateField(help_text='Date of purchase')),
                ('notes', models.TextField(blank=True, default='')),
                ('current_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Latest market price (auto-updated)', max_digits=12)),
                ('last_price_update', models.DateTimeField(blank=True, null=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sell_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['-buy_date', 'symbol'],
            },
        ),
        migrations.CreateModel(
            name='StockPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('date', models.DateField()),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Price History',
                'verbose_name_plural': 'Price Histories',
                'ordering': ['-date'],
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
