# Generated by Codex on 2026-07-07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='buyer',
            field=models.ForeignKey(
                blank=True,
                help_text='Member who bought these shares',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='stock_purchases',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
